# Generated by Django 2.0.1 on 2018-10-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_products',
            name='price',
            field=models.TextField(default='0'),
        ),
    ]
